name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! Tell us what you'd like to see.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: What problem does this feature address?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How should it work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered?
  - type: textarea
    id: extra
    attributes:
      label: Additional context
