[google]
sheet_id = "YOUR_GOOGLE_SHEET_ID_HERE"

[openai]
api_key = "YOUR_OPENAI_API_KEY_HERE"

[gmail]
from_email = "your_email@example.com"

[agent]
master_resume_json = "data/master_resume.json"
bullet_bank_json   = "data/bullets.json"
output_dir         = "outputs"
max_jobs_per_run   = 5

[targets]
greenhouse = ["exampleco"]
lever      = ["examplelever"]
ashby      = ["exampleashby"]
smartrecruiters = ["examplesr"]

[targets_extra]
monster_query = "data analyst"
monster_location = "New York, NY"
dice_query = "data analyst"
dice_location = "New York, NY"
linkedin_search_url = "https://www.linkedin.com/jobs/search/?keywords=data%20analyst&location=New%20York"
indeed_search_url   = "https://www.indeed.com/jobs?q=data+analyst&l=New%20York%2C+NY"
